spring:
  application:
    name: monolith

  threads:
    virtual:
      enabled: true

  cache:
    type: caffeine

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: "SpringBootDevHikariCP"
      maximum-pool-size: 5
      minimum-idle: 2
      idle-timeout: 600000
      max-lifetime: 900000
      connection-timeout: 20000

  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080

exchange-api:
  base-url: ${EXCHANGE_API_URL}
  cache:
    name: currencies
    size: 500
    expiration-hours: 24
  retryer:
    period-seconds: 100
    duration-seconds: 10
    max-attempts: 3
