spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/monolith
    username: monolith
    password: monolith
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_schema: public
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080