services:
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=monolith
      - POSTGRES_PASSWORD=monolith
      - POSTGRES_DB=monolith
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data/standalone:/var/lib/postgresql/data

volumes:
  postgres: