spring:
  application:
    name: gateway

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    service-url:
      defaultZone: ${SPRING_EUREKA_SERVICE}/eureka/